eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://payment-service/payment/doPayment

  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/order/bookOrder
